### ISSUE TITLE
Openwrt: Subtarget MT7628 based boards ???

### ISSUE THREAD

**Issue by Organarh** [openwrt/archive#1]
TP-Link Archer MR-200 V4 Mediatek - MT7628DAN RAM-64 MB Flash-8 MB CPU-580 MHz .
git clone https://github.com/openwrt/openwrt.git ...........
Target System Mediatek Ralink MIPS
Subtarget MT7628 based boards ????    https://ibb.co/wSdfmq9
What to choose instead of TP-Link Archer MR-200 V 4 ???

**Comment by cyberfoxmeow** [comment]
try MT76X8 ?
